[workspace]
members = ["crashpad-sys", "crashpad"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yourusername/crashpad-rs"
rust-version = "1.70"

[workspace.dependencies]
# Common dependencies
thiserror = "1.0"