[package]
name = "xtask"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish = false

[dependencies]
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
xshell = "0.2"
serde_json = "1.0"
regex = "1.0"
chrono = "0.4"
sha256 = "1.5"