name: Build Linux

on:
  pull_request:
  push:
    branches: [ "**" ]

concurrency:
  group: linux-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang pkg-config python3
      - name: Build crashpad-sys
        run: cargo build --package crashpad-sys
      - name: Build crashpad
        run: cargo build --package crashpad
      - name: Unit tests
        run: cargo test --lib
      - name: Create dist package
        run: cargo xtask dist
