name: Build Linux

on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: linux-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 'stable'
      - uses: Swatinem/rust-cache@v2
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential zlib1g-dev libcurl4-openssl-dev clang pkg-config python3
      - name: linux Build
        run: |
          cargo build --package crashpad-sys
          cargo build --package crashpad
