name: Build macOS

on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: macos-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    if: github.actor != 'release-please[bot]'
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 'stable'
      - uses: Swatinem/rust-cache@v2
      - name: macOS Build
        run: |
          cargo build --package crashpad-rs-sys
          cargo build --package crashpad-rs
      - name: test
        run: cargo nextest run