name: Code Quality

on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: code-quality-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 'stable'
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: install-tools
        run: |
          cargo xtask install-tools
      - name: rustfmt
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: test
        run: cargo nextest run