name: Code Quality

on:
  pull_request:

concurrency:
  group: code-quality-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-quality:
    if: github.actor != 'release-please[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 'stable'
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential zlib1g-dev libcurl4-openssl-dev clang pkg-config
      - name: install-tools
        run: |
          cargo xtask install-tools
      - name: rustfmt
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: test
        run: cargo nextest run