name: Manual Release Prebuilt

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g., 1.2.3)'
        required: true
        type: string
      tag_name:
        description: 'Tag name (e.g., v1.2.3)'
        required: true
        type: string
      target:
        description: 'Target platform'
        required: true
        type: choice
        options:
          - all
          - x86_64-pc-windows-msvc
          - aarch64-apple-darwin
          - x86_64-unknown-linux-gnu
          - aarch64-apple-ios
          - aarch64-linux-android

permissions:
  contents: write  # Required for uploading to releases

jobs:
  release-single:
    name: Release ${{ inputs.target }}
    if: inputs.target != 'all'
    runs-on: ${{ fromJSON('{"x86_64-pc-windows-msvc":"windows-latest","aarch64-apple-darwin":"macos-latest","x86_64-unknown-linux-gnu":"ubuntu-latest","aarch64-apple-ios":"macos-latest","aarch64-linux-android":"ubuntu-latest"}')[inputs.target] }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Release prebuilt archive
        uses: ./.github/actions/release-prebuilt-archive
        with:
          target: ${{ inputs.target }}
          version: ${{ inputs.version }}
          tag_name: ${{ inputs.tag_name }}
          needs_ndk: ${{ inputs.target == 'aarch64-linux-android' }}
          
  release-all:
    name: Release All Platforms
    if: inputs.target == 'all'
    strategy:
      fail-fast: false  # Continue other builds even if one fails
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest  
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: aarch64-apple-ios
          - os: ubuntu-latest
            target: aarch64-linux-android
            needs_ndk: true
            
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Release prebuilt archive for ${{ matrix.target }}
        uses: ./.github/actions/release-prebuilt-archive
        with:
          target: ${{ matrix.target }}
          version: ${{ inputs.version }}
          tag_name: ${{ inputs.tag_name }}
          needs_ndk: ${{ matrix.needs_ndk || false }}