name: Update Dependencies

on:
  schedule:
    # Run every Monday at 9:00 AM UTC
    - cron: '0 9 * * MON'
  workflow_dispatch:
    inputs:
      create_pr:
        description: 'Create a pull request with the changes'
        required: false
        default: true
        type: boolean

jobs:
  update-deps:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ github.token }}

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang pkg-config

      - name: Build xtask
        run: cargo build --package xtask

      - name: Update dependencies
        id: update
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          # Configure git
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Run update-deps
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]] && [[ "${{ github.event.inputs.create_pr }}" == "false" ]]; then
            cargo xtask update-deps
          else
            cargo xtask update-deps --create-pr
          fi

      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Report status
        if: steps.check_changes.outputs.changes == 'false'
        run: echo "No dependency updates needed"